//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 03:59:24 PM CEST 
//


package com.example.Tim25Xml.xsd;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Komentar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Komentar"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idVozila" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="komentar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="stanje" type="{http://example.com/voziloservice/xsd}StanjeKomentara"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Komentar", propOrder = {
    "idVozila",
    "komentar",
    "stanje"
})
public class Komentar {

    protected long idVozila;
    @XmlElement(required = true)
    protected String komentar;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StanjeKomentara stanje;

    /**
     * Gets the value of the idVozila property.
     * 
     */
    public long getIdVozila() {
        return idVozila;
    }

    /**
     * Sets the value of the idVozila property.
     * 
     */
    public void setIdVozila(long value) {
        this.idVozila = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentar(String value) {
        this.komentar = value;
    }

    /**
     * Gets the value of the stanje property.
     * 
     * @return
     *     possible object is
     *     {@link StanjeKomentara }
     *     
     */
    public StanjeKomentara getStanje() {
        return stanje;
    }

    /**
     * Sets the value of the stanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link StanjeKomentara }
     *     
     */
    public void setStanje(StanjeKomentara value) {
        this.stanje = value;
    }

}
