//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 03:59:24 PM CEST 
//


package com.example.Tim25Xml.xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StanjeKomentara.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StanjeKomentara"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="OBJAVLJEN"/&gt;
 *     &lt;enumeration value="ODBIJEN"/&gt;
 *     &lt;enumeration value="ODOBREN"/&gt;
 *     &lt;enumeration value="ODGOVOREN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "StanjeKomentara")
@XmlEnum
public enum StanjeKomentara {

    OBJAVLJEN,
    ODBIJEN,
    ODOBREN,
    ODGOVOREN;

    public String value() {
        return name();
    }

    public static StanjeKomentara fromValue(String v) {
        return valueOf(v);
    }

}
